apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: apachetest
  name: apachetest
spec:
  type: NodePort
  ports:
  - name: "81"
    port: 81
    targetPort: 80
    nodePort: 31080
  - name: "444"
    port: 444
    targetPort: 443
    nodePort: 31443
  selector:
    io.kompose.service: apachetest
status:
  loadBalancer: {}

